const CategorieActionTypes = {
  FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  API_CATEGORIES_FAILURE: 'API_CATEGORIES_FAILURE',

  FETCH_SUBCATEGORIES_START: 'FETCH_SUBCATEGORIES_START',
  FETCH_SUBCATEGORIES_SUCCESS: 'FETCH_SUBCATEGORIES_SUCCESS',

  POST_CATEGORIES_START: 'POST_CATEGORIES_START',
  POST_CATEGORIES_SUCCESS: 'POST_CATEGORIES_SUCCESS',

  POST_SUBCATEGORIES_START: 'POST_SUBCATEGORIES_START',
  POST_SUBCATEGORIES_SUCCESS: 'POST_SUBCATEGORIES_SUCCESS',

  EDIT_CATEGORIES_START: 'EDIT_CATEGORIES_START',
  EDIT_CATEGORIES_SUCCESS: 'EDIT_CATEGORIES_SUCCESS',

  EDIT_SUBCATEGORIES_START: 'EDIT_SUBCATEGORIES_START',
  EDIT_SUBCATEGORIES_SUCCESS: 'EDIT_SUBCATEGORIES_SUCCESS',

  DELETE_CATEGORIES_START: 'DELETE_CATEGORIES_START',
  DELETE_CATEGORIES_SUCCESS: 'DELETE_CATEGORIES_SUCCESS',

  DELETE_SUBCATEGORIES_START: 'DELETE_SUBCATEGORIES_START',
  DELETE_SUBCATEGORIES_SUCCESS: 'DELETE_SUBCATEGORIES_SUCCESS',
};

export default CategorieActionTypes;
