const ProductActionTypes = {
  FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',

  FETCH_PRODUCT_START: 'FETCH_PRODUCT_START',
  FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',

  DELETE_PRODUCTS_START: 'DELETE_PRODUCTS_START',
  DELETE_PRODUCTS_SUCCESS: 'DELETE_PRODUCTS_SUCCESS',

  API_PRODUCTS_FAILURE: 'API_PRODUCTS_FAILURE',
};

export default ProductActionTypes;
